# Generated by Django 2.1.7 on 2019-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0001_initial'),
        ('core', '0003_touristspot_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='evaluations',
            field=models.ManyToManyField(to='evaluation.Evaluating'),
        ),
    ]
