# Generated by Django 2.1.7 on 2019-03-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
        ('core', '0004_touristspot_evaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='adresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adresses.Address'),
            preserve_default=False,
        ),
    ]
