# Generated by Django 2.1.7 on 2019-03-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_touristspot_attractions'),
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
    ]
